/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class AssignTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form AssignTaskFrame
     */
    public AssignTaskFrame() {
        initComponents();

        // Add project names to the project combo box
        for (Project p : ProjectManager.projectList) {
            cmbProject.addItem(p.getProjectName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblProject = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTask = new javax.swing.JLabel();
        cmbProject = new javax.swing.JComboBox<>();
        cmbUser = new javax.swing.JComboBox<>();
        cmbTask = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle.setText("Assign Task Screen");

        lblProject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProject.setText("Select Project:");

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setText("Select User:");

        lblTask.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTask.setText("Select Task:");

        cmbProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProjectActionPerformed(evt);
            }
        });

        btnAssign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTask)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProject)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnAssign)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProject)
                    .addComponent(cmbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTask)
                    .addComponent(cmbTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 117, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAssign)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProjectActionPerformed
        // TODO add your handling code here:
        // Clear previous combo box selections
        cmbTask.removeAllItems();
        cmbUser.removeAllItems();

        // Get the selected project name
        String selectedProjectName = (String) cmbProject.getSelectedItem();

        // Find the selected project
        Project selectedProject = null;
        for (Project p : ProjectManager.projectList) {
            if (p.getProjectName().equals(selectedProjectName)) {
                selectedProject = p;
                break;
            }
        }

        // If the project was found, add its tasks to the combo box
        if (selectedProject != null) {
            // Add tasks to combo box
            for (Task t : selectedProject.getTasks()) {
                cmbTask.addItem(t.getTitle());
            }

            // Find the team assigned to the project from the assignment list
            String teamName = null;

            for (Assignment a : ProjectManager.getAssignments()) {
                if (a.getProjectName().equals(selectedProjectName)) {
                    teamName = a.getTeamName();
                    break;
                }
            }

            if (teamName != null) {
                Team team = ProjectManager.findTeamByName(teamName);
                if (team != null) {
                    for (User u : team.getMembers()) {
                        cmbUser.addItem(u.getUsername());
                    }
                }
            }

        }
    }//GEN-LAST:event_cmbProjectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminPanel adminPanel = new AdminPanel(); // Navigate back to the AdminPanel
        adminPanel.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        // Get selected values from combo boxes
        String selectedProjectName = (String) cmbProject.getSelectedItem();
        String selectedTaskTitle = (String) cmbTask.getSelectedItem();
        String selectedUsername = (String) cmbUser.getSelectedItem();

        // Null check
        if (selectedProjectName == null || selectedTaskTitle == null || selectedUsername == null) {
            JOptionPane.showMessageDialog(this, "Please make all selections.");
            return;
        }

        // Find the selected project
        Project selectedProject = null;
        for (Project p : ProjectManager.projectList) {
            if (p.getProjectName().equals(selectedProjectName)) {
                selectedProject = p;
                break;
            }
        }

        // If project not found
        if (selectedProject == null) {
            JOptionPane.showMessageDialog(this, "Project not found.");
            return;
        }

        // Find the selected task
        Task selectedTask = null;
        for (Task t : selectedProject.getTasks()) {
            if (t.getTitle().equals(selectedTaskTitle)) {
                selectedTask = t;
                break;
            }
        }

        // Find the assigned team
        String teamName = null;
        for (Assignment a : ProjectManager.getAssignments()) {
            if (a.getProjectName().equals(selectedProjectName)) {
                teamName = a.getTeamName();
                break;
            }
        }

        Team assignedTeam = ProjectManager.findTeamByName(teamName);

        if (assignedTeam == null) {
            JOptionPane.showMessageDialog(this, "Team not found.");
            return;
        }

        // Find the selected user
        User selectedUser = null;
        for (User u : assignedTeam.getMembers()) {
            if (u.getUsername().equals(selectedUsername)) {
                selectedUser = u;
                break;
            }
        }

        if (selectedUser == null || selectedTask == null) {
            JOptionPane.showMessageDialog(this, "Task or user not found.");
            return;
        }

        // Rule: Check if the task is already assigned
        if (selectedTask.getAssignedUser() != null) {
            JOptionPane.showMessageDialog(this, "This task is already assigned.");
            return;
        }

        // Rule: Check if the user already has a task in the project
        for (Task t : selectedProject.getTasks()) {
            if (selectedUser.equals(t.getAssignedUser())) {
                JOptionPane.showMessageDialog(this, "This user already has a task assigned in this project.");
                return;
            }
        }

        // Assign the task to the user
        selectedTask.setAssignedUser(selectedUser);
        JOptionPane.showMessageDialog(this, "Task successfully assigned!");
    }//GEN-LAST:event_btnAssignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbProject;
    private javax.swing.JComboBox<String> cmbTask;
    private javax.swing.JComboBox<String> cmbUser;
    private javax.swing.JLabel lblProject;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
