package midproject1;

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author asus
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterUsername = new javax.swing.JLabel();
        lblTitleLoginScreen = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblEnterPassword = new javax.swing.JLabel();
        lblSignUpQuestion = new javax.swing.JLabel();
        btnsignup = new javax.swing.JButton();
        btnuserlogin = new javax.swing.JButton();
        btnadminlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEnterUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnterUsername.setText("Enter username:");

        lblTitleLoginScreen.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitleLoginScreen.setText("Login Screen");

        lblEnterPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnterPassword.setText("Enter password:");

        lblSignUpQuestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSignUpQuestion.setForeground(new java.awt.Color(102, 102, 255));
        lblSignUpQuestion.setText("Do not you have an account?");

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsignup.setText("Sign up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        btnuserlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnuserlogin.setText("User Login");
        btnuserlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserloginActionPerformed(evt);
            }
        });

        btnadminlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadminlogin.setText("Admin Login");
        btnadminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblEnterPassword))
                            .addComponent(lblEnterUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername)
                            .addComponent(jPasswordField1)
                            .addComponent(btnuserlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnadminlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleLoginScreen)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblSignUpQuestion)
                                .addGap(18, 18, 18)
                                .addComponent(btnsignup)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitleLoginScreen)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterUsername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterPassword))
                .addGap(18, 18, 18)
                .addComponent(btnuserlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadminlogin)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignUpQuestion)
                    .addComponent(btnsignup))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens the registration screen when the user clicks "Sign up".
     */
    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RegisterScreen().setVisible(true);
    }//GEN-LAST:event_btnsignupActionPerformed

    /**
     * Handles login attempt for regular users. It checks if the username and
     * password match any user in the system.
     */
    private void btnuserloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserloginActionPerformed
        // TODO add your handling code here:
        String username = txtusername.getText(); // Gets the entered username
        String password = new String(jPasswordField1.getPassword()); // Gets the entered password

        // Validation check to ensure both fields are filled
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password!");
            return;
        }

        try {
            boolean userFound = false;
            // Iterate over the user list to find a matching username
            for (User u : UserManager.userList) {
                if (u.getUsername().equals(username)) {
                    userFound = true;

                    // Check if the entered password matches the stored password
                    if (u.getPassword().equals(password)) {
                        UserManager.setUser(u);  // Set the currently logged in user
                        User.currentUser = u; // Save globally
                        JOptionPane.showMessageDialog(this, "Login successful!");
                        // Open user dashboard
                        setVisible(false); // Hide the login screen
                        UserInfoScreen userFrame = new UserInfoScreen();
                        userFrame.setVisible(true);
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect password!", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            if (!userFound) {
                // If no matching user is found
                JOptionPane.showMessageDialog(this, "There is no user. Please sign up first!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred during login:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnuserloginActionPerformed

    /**
     * Handles login attempt for the admin user. Admin credentials are
     * hardcoded.
     */
    private void btnadminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminloginActionPerformed
        // TODO add your handling code here:
        String username = txtusername.getText(); // Get entered admin username
        String password = new String(jPasswordField1.getPassword()); // Get entered admin password

        // Validate username and password fields
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password!"); // Prompt for missing fields
            return;
        }

        if (username.equals("esila04") && password.equals("2004")) { // Admin username and password check
            JOptionPane.showMessageDialog(this, "Admin login successful!"); // Success message
            new AdminPanel().setVisible(true); // Open admin panel
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Admin username or password is incorrect!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnadminloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnuserlogin;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblEnterPassword;
    private javax.swing.JLabel lblEnterUsername;
    private javax.swing.JLabel lblSignUpQuestion;
    private javax.swing.JLabel lblTitleLoginScreen;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
